#!/bin/bash

set -eux

# Bump the version according to conventional commits.
version="$(uv run cz bump --get-next)"
uv version "$version"

# Update the changelog.
today=$(date +%Y-%m-%d)
sed -i "s/## Unreleased/## Version $version — $today/" docs/changelog.md

# Commit and tag.
git ca -m "chore: bump version to $version"
git tag "$version"

# Upload the code.
git push
git push --tags

# Publish the built project.
uv build
uv publish \
    --token "$PYPI_TOKEN_GEO_ACTIVITY_PLAYGROUND" \
    "dist/geo_activity_playground-$version-py3-none-any.whl"

# Deploy documentation.
uv run mkdocs gh-deploy

# Create a GitHub release.
uv run python3 extract-changelog.py docs/changelog.md "$version" > /tmp/release_notes.md
gh release create "$version" -F release_notes.md -t "$version"
rm /tmp/release_notes.md