#!/bin/bash

set -eux

version=$(grep -m 1 '^version = ' pyproject.toml | cut -d '"' -f 2)
today=$(date +%Y-%m-%d)

sed -i "s/## Unreleased/## Version $version — $today/" docs/changelog.md
git ca -m "chore: bump version to $version"

# Upload the code.
git push

# Tag this version and upload the tag.
git tag "$version"
git push --tags

uv build
uv publish \
    --token "$PYPI_TOKEN_GEO_ACTIVITY_PLAYGROUND" \
    "dist/geo_activity_playground-$version.tar.gz" \
    "dist/geo_activity_playground-$version-py3-none-any.whl"
uv run mkdocs gh-deploy

uv run python3 extract-changelog.py docs/changelog.md "$version" > /tmp/release_notes.md
gh release create "$version" -F release_notes.md -t "$version"
rm /tmp/release_notes.md