#!/bin/bash

set -eu

version=$(uv version --short)

npm run docs:build
dist="docs/.vitepress/dist"

git -C "$dist" init
git -C "$dist" add -A
git -C "$dist" commit -m "docs: deploy documentation for $version"
origin="$(git remote get-url origin)"
git -C "$dist" push -f "$origin" HEAD:gh-pages
rm -rf "$dist/.git"
