# Generated by Django 5.1.7 on 2025-03-28 18:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("gap_app", "0002_equipment_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="purchase_date",
            field=models.DateField(null=True),
        ),
    ]
