# Generated by Django 5.1.7 on 2025-03-28 18:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("gap_app", "0003_equipment_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="kind",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
