# Generated by Django 5.1.7 on 2025-03-28 18:53
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("gap_app", "0004_alter_equipment_name_alter_kind_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="elapsed_time",
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="equipment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gap_app.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gap_app.kind",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="moving_time",
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="start",
            field=models.DateTimeField(null=True),
        ),
    ]
