# Generated by Django 5.1.7 on 2025-03-28 19:05
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gap_app",
            "0006_alter_activity_elapsed_time_alter_activity_equipment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="distance_km",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="activity",
            name="elevation_gain",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="end_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="end_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="start_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="steps",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
