# Generated by Django 5.1.7 on 2025-03-29 07:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("gap_app", "0007_activity_calories_activity_distance_km_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="kind",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
