from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0163a57011d8"
down_revision: str | None = "73bf4cd0eded"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segment_matches", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("unique_segment_activity_match"), type_="unique"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segment_matches", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("unique_segment_activity_match"), ["segment_id", "activity_id"]
        )

    # ### end Alembic commands ###
