"""Add foreign keys

Revision ID: 11d2684d70e4
Revises: 5b93488ffcc1
Create Date: 2024-08-29 09:30:37.516029

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "11d2684d70e4"
down_revision: Union[str, None] = "5b93488ffcc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "equipment_id", "equipments", ["equipment_id"], ["id"]
        )
        batch_op.create_foreign_key("kind_id", "kinds", ["kind_id"], ["id"])

    with op.batch_alter_table("tile_visits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activity_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("tile_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("tile_id", "tiles", ["tile_id"], ["id"])
        batch_op.create_foreign_key(
            "activity_id", "activities", ["activity_id"], ["id"]
        )

    with op.batch_alter_table("tiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_visit_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "first_visit_id", "activities", ["first_visit_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tiles", schema=None) as batch_op:
        batch_op.drop_constraint("first_visit_id", type_="foreignkey")
        batch_op.drop_column("first_visit_id")

    with op.batch_alter_table("tile_visits", schema=None) as batch_op:
        batch_op.drop_constraint("activity_id", type_="foreignkey")
        batch_op.drop_constraint("tile_id", type_="foreignkey")
        batch_op.drop_column("tile_id")
        batch_op.drop_column("activity_id")

    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_constraint("kind_id", type_="foreignkey")
        batch_op.drop_constraint("equipment_id", type_="foreignkey")

    # ### end Alembic commands ###
