from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c5d9426ec31"
down_revision: str | None = "204f14d48177"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_size_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("max_cluster_size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cluster_size_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cluster_size_history_zoom"), ["zoom"], unique=False
        )

    op.create_table(
        "explorer_square",
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("square_x", sa.Integer(), nullable=True),
        sa.Column("square_y", sa.Integer(), nullable=True),
        sa.Column("max_square_size", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("zoom"),
    )
    op.create_table(
        "square_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.Column("max_square_size", sa.Integer(), nullable=False),
        sa.Column("square_x", sa.Integer(), nullable=False),
        sa.Column("square_y", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("square_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_square_history_zoom"), ["zoom"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("square_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_square_history_zoom"))

    op.drop_table("square_history")
    op.drop_table("explorer_square")
    with op.batch_alter_table("cluster_size_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cluster_size_history_zoom"))

    op.drop_table("cluster_size_history")
    # ### end Alembic commands ###
