from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "204f14d48177"
down_revision: str | None = "3e34e2523c74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_tile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("tile_x", sa.Integer(), nullable=False),
        sa.Column("tile_y", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], name="activity_tile_activity_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_tile", schema=None) as batch_op:
        batch_op.create_index(
            "idx_activity_tile_zoom_tile", ["zoom", "tile_x", "tile_y"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_tile_activity_id"), ["activity_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_tile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_tile_activity_id"))
        batch_op.drop_index("idx_activity_tile_zoom_tile")

    op.drop_table("activity_tile")
    # ### end Alembic commands ###
