from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3046ae476995"
down_revision: str | None = "67debf542316"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segment_matches", schema=None) as batch_op:
        batch_op.add_column(sa.Column("power_avg", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segment_matches", schema=None) as batch_op:
        batch_op.drop_column("power_avg")

    # ### end Alembic commands ###
