"""Add Activity.updated

Revision ID: 5b93488ffcc1
Revises: 847e5c912b68
Create Date: 2024-08-29 09:04:27.094323

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5b93488ffcc1"
down_revision: Union[str, None] = "847e5c912b68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activities", sa.Column("updated", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activities", "updated")
    # ### end Alembic commands ###
