from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "637be1ebb841"
down_revision: str | None = "3046ae476995"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tile_visits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tile_visits_last_activity_id"),
            ["last_activity_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tile_visits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tile_visits_last_activity_id"))

    # ### end Alembic commands ###
