from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "674e65a1d2fe"
down_revision: str | None = "1c5d9426ec31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hammerhead_auth", schema=None) as batch_op:
        batch_op.add_column(sa.Column("client_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("client_secret", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("client_code", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hammerhead_auth", schema=None) as batch_op:
        batch_op.drop_column("client_code")
        batch_op.drop_column("client_secret")
        batch_op.drop_column("client_id")

    # ### end Alembic commands ###
