from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "67c63532549d"
down_revision: Union[str, None] = "21967c9ccd81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tile_first_visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("tile_x", sa.Integer(), nullable=False),
        sa.Column("tile_y", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], name="tile_first_visit_activity_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "zoom", "tile_x", "tile_y", name="unique_tile_first_visit_per_zoom"
        ),
    )
    with op.batch_alter_table("tile_first_visits", schema=None) as batch_op:
        batch_op.create_index(
            "idx_tile_first_visits_zoom_tile",
            ["zoom", "tile_x", "tile_y"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_tile_first_visits_activity_id"),
            ["activity_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tile_first_visits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tile_first_visits_activity_id"))
        batch_op.drop_index("idx_tile_first_visits_zoom_tile")

    op.drop_table("tile_first_visits")
    # ### end Alembic commands ###
