from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "73bf4cd0eded"
down_revision: Union[str, None] = "eecb7ba15f7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "segment_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], name="segment_check_activity_id"
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"], ["segments.id"], name="segment_check_segment_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "segment_id", "activity_id", name="unique_segment_activity_check"
        ),
    )
    with op.batch_alter_table("segment_checks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_segment_checks_activity_id"), ["activity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_segment_checks_segment_id"), ["segment_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segment_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segment_checks_segment_id"))
        batch_op.drop_index(batch_op.f("ix_segment_checks_activity_id"))

    op.drop_table("segment_checks")
    # ### end Alembic commands ###
