"""Init

Revision ID: 847e5c912b68
Revises: 
Create Date: 2024-08-29 09:01:54.036261

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "847e5c912b68"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("consider_for_achievements", sa.Boolean(), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("elapsed_time", sa.Interval(), nullable=False),
        sa.Column("end_latitude", sa.Float(), nullable=True),
        sa.Column("end_longitude", sa.Float(), nullable=True),
        sa.Column("moving_time", sa.Interval(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("start_latitude", sa.Float(), nullable=True),
        sa.Column("start_longitude", sa.Float(), nullable=True),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "equipments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "kinds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tile_visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tiles_x"), "tiles", ["x"], unique=False)
    op.create_index(op.f("ix_tiles_y"), "tiles", ["y"], unique=False)
    op.create_index(op.f("ix_tiles_zoom"), "tiles", ["zoom"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tiles_zoom"), table_name="tiles")
    op.drop_index(op.f("ix_tiles_y"), table_name="tiles")
    op.drop_index(op.f("ix_tiles_x"), table_name="tiles")
    op.drop_table("tiles")
    op.drop_table("tile_visits")
    op.drop_table("kinds")
    op.drop_table("equipments")
    op.drop_table("activities")
    # ### end Alembic commands ###
