from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "93cc82ad1b60"
down_revision: Union[str, None] = "e02e27876deb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plot_specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("mark", sa.String(), nullable=True),
        sa.Column("x", sa.String(), nullable=True),
        sa.Column("y", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("shape", sa.String(), nullable=True),
        sa.Column("size", sa.String(), nullable=True),
        sa.Column("row", sa.String(), nullable=True),
        sa.Column("opacity", sa.String(), nullable=True),
        sa.Column("column", sa.String(), nullable=True),
        sa.Column("facet", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plot_specs")
    # ### end Alembic commands ###
