from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9cf4b4d4c9da"
down_revision: Union[str, None] = "0163a57011d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kinds", schema=None) as batch_op:
        batch_op.add_column(sa.Column("replaced_by_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "kind_replaced_by_id", "kinds", ["replaced_by_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kinds", schema=None) as batch_op:
        batch_op.drop_constraint("kind_replaced_by_id", type_="foreignkey")
        batch_op.drop_column("replaced_by_id")

    # ### end Alembic commands ###
