from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d455cc64bcf"
down_revision: str | None = "9cf4b4d4c9da"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("extraction_regex", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("extraction_destructive", sa.Boolean(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_column("extraction_destructive")
        batch_op.drop_column("extraction_regex")

    # ### end Alembic commands ###
