from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b74f5a37cff9"
down_revision: Union[str, None] = "b7d63e7cd0de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("coordinates_geojson", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "segment_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("segment_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("entry_index", sa.Integer(), nullable=False),
        sa.Column("entry_time", sa.DateTime(), nullable=True),
        sa.Column("exit_index", sa.Integer(), nullable=False),
        sa.Column("exit_time", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Interval(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], name="segment_match_activity_id"
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"], ["segments.id"], name="segment_match_segment_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "segment_id", "activity_id", name="unique_segment_activity_match"
        ),
    )
    with op.batch_alter_table("segment_matches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_segment_matches_activity_id"), ["activity_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_segment_matches_segment_id"), ["segment_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segment_matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segment_matches_segment_id"))
        batch_op.drop_index(batch_op.f("ix_segment_matches_activity_id"))

    op.drop_table("segment_matches")
    op.drop_table("segments")
    # ### end Alembic commands ###
