from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b7d63e7cd0de"
down_revision: Union[str, None] = "21967c9ccd81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tile_visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("tile_x", sa.Integer(), nullable=False),
        sa.Column("tile_y", sa.Integer(), nullable=False),
        sa.Column("first_activity_id", sa.Integer(), nullable=False),
        sa.Column("first_time", sa.DateTime(), nullable=True),
        sa.Column("last_activity_id", sa.Integer(), nullable=False),
        sa.Column("last_time", sa.DateTime(), nullable=True),
        sa.Column("visit_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["first_activity_id"],
            ["activities.id"],
            name="tile_visit_first_activity_id",
        ),
        sa.ForeignKeyConstraint(
            ["last_activity_id"], ["activities.id"], name="tile_visit_last_activity_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "zoom", "tile_x", "tile_y", name="unique_tile_visit_per_zoom"
        ),
    )
    with op.batch_alter_table("tile_visits", schema=None) as batch_op:
        batch_op.create_index(
            "idx_tile_visits_zoom_tile", ["zoom", "tile_x", "tile_y"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tile_visits_first_activity_id"),
            ["first_activity_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tile_visits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tile_visits_first_activity_id"))
        batch_op.drop_index("idx_tile_visits_zoom_tile")

    op.drop_table("tile_visits")
    # ### end Alembic commands ###
