"""Make names unique

Revision ID: c193b1cbd516
Revises: 11d2684d70e4
Create Date: 2024-08-29 09:43:46.355125

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "c193b1cbd516"
down_revision: Union[str, None] = "11d2684d70e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipments", schema=None) as batch_op:
        batch_op.create_unique_constraint("equipments_name", ["name"])

    with op.batch_alter_table("kinds", schema=None) as batch_op:
        batch_op.create_unique_constraint("kinds_name", ["name"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kinds", schema=None) as batch_op:
        batch_op.drop_constraint("kinds_name", type_="unique")

    with op.batch_alter_table("equipments", schema=None) as batch_op:
        batch_op.drop_constraint("equipments_name", type_="unique")

    # ### end Alembic commands ###
