from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da404080b59c"
down_revision: str | None = "85c2e043924a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_activity_import",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metadata_extraction_regexes", sa.JSON(), nullable=False),
        sa.Column("ignore_suffixes", sa.JSON(), nullable=False),
        sa.Column("time_diff_threshold_seconds", sa.Integer(), nullable=True),
        sa.Column("reliable_elevation_measurements", sa.Boolean(), nullable=False),
        sa.Column("kind_renames", sa.JSON(), nullable=False),
        sa.Column("segment_max_distance", sa.Integer(), nullable=False),
        sa.Column("segment_split_distance", sa.Integer(), nullable=False),
        sa.Column("upload_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_heart_rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("heart_rate_resting", sa.Integer(), nullable=False),
        sa.Column("heart_rate_maximum", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("map_tile_url", sa.String(), nullable=False),
        sa.Column("map_tile_attribution", sa.String(), nullable=False),
        sa.Column("map_style_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_strava",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strava_client_id", sa.Integer(), nullable=False),
        sa.Column("strava_client_secret", sa.String(), nullable=False),
        sa.Column("strava_client_code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config_ui",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cluster_color_strategy", sa.String(), nullable=False),
        sa.Column("color_scheme_for_counts", sa.String(), nullable=False),
        sa.Column("color_scheme_for_kind", sa.String(), nullable=False),
        sa.Column("color_scheme_for_heatmap", sa.String(), nullable=False),
        sa.Column("color_strategy_max_cluster_color", sa.String(), nullable=False),
        sa.Column(
            "color_strategy_max_cluster_other_color", sa.String(), nullable=False
        ),
        sa.Column("color_strategy_visited_color", sa.String(), nullable=False),
        sa.Column("color_strategy_cmap_opacity", sa.Float(), nullable=False),
        sa.Column("eighth_marker_min_distance_km", sa.Float(), nullable=False),
        sa.Column("eighth_marker_min_duration_hours", sa.Float(), nullable=False),
        sa.Column("explorer_zoom_levels", sa.JSON(), nullable=False),
        sa.Column("show_progress_markers", sa.Boolean(), nullable=False),
        sa.Column("visible_table_columns", sa.JSON(), nullable=False),
        sa.Column("search_map_tiles_per_page", sa.Integer(), nullable=False),
        sa.Column("heatmap_cache_min_activities", sa.Integer(), nullable=False),
        sa.Column("sharepic_suppressed_fields", sa.JSON(), nullable=False),
        sa.Column("kinds_without_achievements", sa.JSON(), nullable=False),
        sa.Column("preferred_language", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "privacy_zones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("points", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("privacy_zones")
    op.drop_table("config_ui")
    op.drop_table("config_strava")
    op.drop_table("config_map")
    op.drop_table("config_heart_rate")
    op.drop_table("config_activity_import")
    # ### end Alembic commands ###
