from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e02e27876deb"
down_revision: Union[str, None] = "451e7836b53d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("square_planner_bookmarks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("square_planner_bookmarks", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
