from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e45409f4ebd9"
down_revision: str | None = "c5be2d6a88e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heatmap_tile_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("tile_x", sa.Integer(), nullable=False),
        sa.Column("tile_y", sa.Integer(), nullable=False),
        sa.Column("search_query_id", sa.Integer(), nullable=True),
        sa.Column("counts", sa.LargeBinary(), nullable=False),
        sa.Column("included_activity_ids", sa.JSON(), nullable=False),
        sa.Column("num_activities", sa.Integer(), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["search_query_id"],
            ["stored_search_queries.id"],
            name="heatmap_cache_search_query_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "zoom",
            "tile_x",
            "tile_y",
            "search_query_id",
            name="uq_heatmap_tile_cache_tile_query",
        ),
    )
    with op.batch_alter_table("heatmap_tile_cache", schema=None) as batch_op:
        batch_op.create_index(
            "idx_heatmap_tile_cache_lookup",
            ["zoom", "tile_x", "tile_y", "search_query_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_heatmap_tile_cache_search_query_id"),
            ["search_query_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("heatmap_tile_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_heatmap_tile_cache_search_query_id"))
        batch_op.drop_index("idx_heatmap_tile_cache_lookup")

    op.drop_table("heatmap_tile_cache")
    # ### end Alembic commands ###
