from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "eecb7ba15f7e"
down_revision: Union[str, None] = "b74f5a37cff9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("coordinates_json", sa.Text(), nullable=False))
        batch_op.drop_column("coordinates_geojson")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("coordinates_geojson", sa.TEXT(), nullable=False))
        batch_op.drop_column("coordinates_json")

    # ### end Alembic commands ###
