"""Use many-to-many association

Revision ID: f9e2aafcd33b
Revises: c193b1cbd516
Create Date: 2024-08-29 10:18:34.227810

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f9e2aafcd33b"
down_revision: Union[str, None] = "c193b1cbd516"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tile_visits_auto",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("tile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], name="activity_id"),
        sa.ForeignKeyConstraint(["tile_id"], ["tiles.id"], name="tile_id"),
        sa.PrimaryKeyConstraint("activity_id", "tile_id"),
    )
    op.drop_table("tile_visits")
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("equipment_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("kind_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("kind_id", "kinds", ["kind_id"], ["id"])
        batch_op.create_foreign_key(
            "equipment_id", "equipments", ["equipment_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_constraint("equipment_id", type_="foreignkey")
        batch_op.drop_constraint("kind_id", type_="foreignkey")
        batch_op.drop_column("kind_id")
        batch_op.drop_column("equipment_id")

    op.create_table(
        "tile_visits",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("activity_id", sa.INTEGER(), nullable=False),
        sa.Column("tile_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activities.id"], name="activity_id"),
        sa.ForeignKeyConstraint(["tile_id"], ["tiles.id"], name="tile_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("tile_visits_auto")
    # ### end Alembic commands ###
