from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a91b4fd93af"
down_revision: str | None = "9222d422f530"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("currency", sa.String(), server_default="", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.drop_column("currency")

    # ### end Alembic commands ###
