from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32fb4c78f594"
down_revision: str | None = "98d098ca0e68"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("usage_km", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("equipment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipments.id"], name="equipment_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recurring_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("interval_days", sa.Integer(), nullable=True),
        sa.Column("interval_km", sa.Integer(), nullable=True),
        sa.Column("equipment_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipments.id"], name="equipment_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "maintenance_action_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("caption", sa.String(), nullable=True),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("maintenance_action_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["maintenance_action_id"],
            ["maintenance_actions.id"],
            name="maintenance_action_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_executions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("usage_km", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["recurring_tasks.id"], name="task_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_executions")
    op.drop_table("maintenance_action_photos")
    op.drop_table("recurring_tasks")
    op.drop_table("maintenance_actions")
    # ### end Alembic commands ###
