from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e34e2523c74"
down_revision: str | None = "637be1ebb841"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_membership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("tile_x", sa.Integer(), nullable=False),
        sa.Column("tile_y", sa.Integer(), nullable=False),
        sa.Column("cluster_x", sa.Integer(), nullable=False),
        sa.Column("cluster_y", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "zoom", "tile_x", "tile_y", name="uq_cluster_membership_per_zoom"
        ),
    )
    with op.batch_alter_table("cluster_membership", schema=None) as batch_op:
        batch_op.create_index(
            "idx_cluster_membership_zoom_cluster",
            ["zoom", "cluster_x", "cluster_y"],
            unique=False,
        )
        batch_op.create_index(
            "idx_cluster_membership_zoom_tile",
            ["zoom", "tile_x", "tile_y"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster_membership", schema=None) as batch_op:
        batch_op.drop_index("idx_cluster_membership_zoom_tile")
        batch_op.drop_index("idx_cluster_membership_zoom_cluster")

    op.drop_table("cluster_membership")
    # ### end Alembic commands ###
