from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52840fd4aab2"
down_revision: str | None = "e7c3afa009a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "color_strategy_new_tile_color",
                sa.String(),
                server_default="#ff7700ff",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "color_strategy_new_cluster_color",
                sa.String(),
                server_default="#0066ffff",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.drop_column("color_strategy_new_cluster_color")
        batch_op.drop_column("color_strategy_new_tile_color")

    # ### end Alembic commands ###
