"""Add metadata provenance layers to Activity.

Name, kind and equipment are split into a file layer, a path layer and a user layer.
The user layer wins, so re-importing an activity can refresh the lower layers without
discarding manual edits.

Existing rows carry no record of where their values came from. The path layer is
therefore recomputed from the configured regexes, and a user override is written only
where the current value differs from what the file and path layers yield -- which is
the only evidence of a manual edit that the old schema left behind.
"""

import json
import pathlib
import re
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

ACTIVITY_DIR = pathlib.Path("Activities")
DEFAULT_UNKNOWN_NAME = "Unknown"


# revision identifiers, used by Alembic.
revision: str = "7526d4b8323c"
down_revision: str | None = "93e6a337660d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("equipment_from_file", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("name_from_path", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("kind_from_path", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("equipment_from_path", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("name_from_user", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("equipment_from_user_id", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("kind_from_user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "equipment_from_user_id", "equipments", ["equipment_from_user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "kind_from_user_id", "kinds", ["kind_from_user_id"], ["id"]
        )

    # ### end Alembic commands ###

    _backfill_layers()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_constraint("kind_from_user_id", type_="foreignkey")
        batch_op.drop_constraint("equipment_from_user_id", type_="foreignkey")
        batch_op.drop_column("kind_from_user_id")
        batch_op.drop_column("equipment_from_user_id")
        batch_op.drop_column("name_from_user")
        batch_op.drop_column("equipment_from_path")
        batch_op.drop_column("kind_from_path")
        batch_op.drop_column("name_from_path")
        batch_op.drop_column("equipment_from_file")

    # ### end Alembic commands ###


def _metadata_from_path(path: str, regexes: list[str]) -> dict[str, str]:
    try:
        relative = pathlib.Path(path).relative_to(ACTIVITY_DIR).as_posix()
    except ValueError:
        relative = pathlib.Path(path).as_posix()
    for regex in regexes:
        try:
            match = re.search(regex, relative)
        except re.error:
            continue
        if match:
            return {key: value for key, value in match.groupdict().items() if value}
    return {}


def _stem_of(path: str | None) -> str | None:
    if not path:
        return None
    file = pathlib.Path(path)
    return file.name.removesuffix("".join(file.suffixes)) or None


def _backfill_layers() -> None:
    bind = op.get_bind()

    regexes: list[str] = []
    row = bind.execute(
        sa.text(
            "SELECT metadata_extraction_regexes FROM config_activity_import LIMIT 1"
        )
    ).first()
    if row is not None and row[0]:
        raw = row[0]
        regexes = json.loads(raw) if isinstance(raw, str) else raw

    def names_by_id(table: str) -> dict[int, str]:
        return dict(bind.execute(sa.text(f"SELECT id, name FROM {table}")).all())

    kind_by_id = names_by_id("kinds")
    equipment_by_id = names_by_id("equipments")
    kind_by_name = {name: id_ for id_, name in kind_by_id.items()}

    kind_alias = dict(
        bind.execute(
            sa.text(
                "SELECT id, replaced_by_id FROM kinds WHERE replaced_by_id IS NOT NULL"
            )
        ).all()
    )

    def canonical_kind_name(name: str | None) -> str | None:
        id_ = kind_by_name.get(name) if name else None
        if id_ is None:
            return name
        return kind_by_id.get(kind_alias.get(id_, id_), name)

    activities = bind.execute(
        sa.text(
            "SELECT id, path, name, name_from_file, kind_from_file, kind_id, equipment_id "
            "FROM activities"
        )
    ).all()

    for (
        activity_id,
        path,
        name,
        name_from_file,
        kind_from_file,
        kind_id,
        equipment_id,
    ) in activities:
        meta = _metadata_from_path(path, regexes) if path else {}
        name_from_path = meta.get("name")
        kind_from_path = meta.get("kind")
        equipment_from_path = meta.get("equipment")

        derived_name = name_from_path or name_from_file or _stem_of(path)
        derived_kind = canonical_kind_name(
            kind_from_path or kind_from_file or DEFAULT_UNKNOWN_NAME
        )
        derived_equipment = equipment_from_path or DEFAULT_UNKNOWN_NAME

        current_kind = kind_by_id.get(kind_id)
        current_equipment = equipment_by_id.get(equipment_id)

        name_from_user = name if name != derived_name else None
        kind_from_user_id = kind_id if current_kind != derived_kind else None
        equipment_from_user_id = (
            equipment_id if current_equipment != derived_equipment else None
        )

        bind.execute(
            sa.text(
                "UPDATE activities SET "
                "name_from_path = :name_from_path, "
                "kind_from_path = :kind_from_path, "
                "equipment_from_path = :equipment_from_path, "
                "name_from_user = :name_from_user, "
                "kind_from_user_id = :kind_from_user_id, "
                "equipment_from_user_id = :equipment_from_user_id "
                "WHERE id = :id"
            ),
            {
                "id": activity_id,
                "name_from_path": name_from_path,
                "kind_from_path": kind_from_path,
                "equipment_from_path": equipment_from_path,
                "name_from_user": name_from_user,
                "kind_from_user_id": kind_from_user_id,
                "equipment_from_user_id": equipment_from_user_id,
            },
        )
