from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85c2e043924a"
down_revision: str | None = "1f39d5f38043"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hammerhead_auth", schema=None) as batch_op:
        batch_op.add_column(sa.Column("redirect_uri", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hammerhead_auth", schema=None) as batch_op:
        batch_op.drop_column("redirect_uri")

    # ### end Alembic commands ###
