from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9222d422f530"
down_revision: str | None = "60dbb2d3c4ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_exclusions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("upstream_id", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("last_attempt", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "upstream_id"),
    )
    op.execute(
        "INSERT INTO import_exclusions "
        "(source, upstream_id, path, reason, error_message, last_attempt) "
        "SELECT 'directory', file_hash, path, reason, error_message, last_attempt "
        "FROM broken_activity_files "
        "GROUP BY file_hash"
    )
    op.drop_table("broken_activity_files")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broken_activity_files",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("path", sa.VARCHAR(), nullable=False),
        sa.Column("file_hash", sa.VARCHAR(), nullable=False),
        sa.Column("reason", sa.VARCHAR(), nullable=False),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column("last_attempt", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.drop_table("import_exclusions")
    # ### end Alembic commands ###
