from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93e6a337660d"
down_revision: str | None = "fcc797055eac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "explorer_grid_line_color",
                sa.String(),
                server_default="#80808080",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "explorer_grid_line_min_width_px",
                sa.Integer(),
                server_default="64",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.drop_column("explorer_grid_line_min_width_px")
        batch_op.drop_column("explorer_grid_line_color")

    # ### end Alembic commands ###
