from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98d098ca0e68"
down_revision: str | None = "da404080b59c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("picture_filename", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("equipments", schema=None) as batch_op:
        batch_op.drop_column("picture_filename")

    # ### end Alembic commands ###
