from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca66a2c1fb21"
down_revision: str | None = "c23574370639"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route_distances",
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("reference_activity_id", sa.Integer(), nullable=False),
        sa.Column("p25", sa.Float(), nullable=True),
        sa.Column("p50", sa.Float(), nullable=True),
        sa.Column("p75", sa.Float(), nullable=True),
        sa.Column("p95", sa.Float(), nullable=True),
        sa.Column("p100", sa.Float(), nullable=True),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activities.id"], name="route_distance_activity_id"
        ),
        sa.ForeignKeyConstraint(
            ["reference_activity_id"],
            ["activities.id"],
            name="route_distance_reference_activity_id",
        ),
        sa.PrimaryKeyConstraint("activity_id", "reference_activity_id"),
    )
    with op.batch_alter_table("route_distances", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_route_distances_reference_activity_id"),
            ["reference_activity_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("route_distances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_route_distances_reference_activity_id"))

    op.drop_table("route_distances")
    # ### end Alembic commands ###
