from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d2b9dd4dfc92"
down_revision: str | None = "a7dcbe76d7c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "street_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("osm_id", sa.BigInteger(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("osm_id"),
    )
    op.create_table(
        "street_regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("tile_x", sa.Integer(), nullable=False),
        sa.Column("tile_y", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "zoom", "tile_x", "tile_y", name="unique_street_region_tile"
        ),
    )
    op.create_table(
        "street_ways",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("osm_id", sa.BigInteger(), nullable=False),
        sa.Column("highway", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("osm_id"),
    )
    op.create_table(
        "street_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("way_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("lat1", sa.Float(), nullable=False),
        sa.Column("lon1", sa.Float(), nullable=False),
        sa.Column("lat2", sa.Float(), nullable=False),
        sa.Column("lon2", sa.Float(), nullable=False),
        sa.Column("length_m", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["way_id"], ["street_ways.id"], name="street_chunk_way_id"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("way_id", "seq", name="unique_street_chunk_seq"),
    )
    with op.batch_alter_table("street_chunks", schema=None) as batch_op:
        batch_op.create_index(
            "idx_street_chunks_bbox", ["lat1", "lon1", "lat2", "lon2"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_street_chunks_way_id"), ["way_id"], unique=False
        )

    op.create_table(
        "activity_street_chunk_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("way_id", sa.Integer(), nullable=False),
        sa.Column("seq_start", sa.Integer(), nullable=False),
        sa.Column("seq_end", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("time_start", sa.DateTime(), nullable=True),
        sa.Column("time_end", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name="activity_street_chunk_run_activity_id",
        ),
        sa.ForeignKeyConstraint(
            ["way_id"], ["street_ways.id"], name="activity_street_chunk_run_way_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_street_chunk_runs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_activity_street_chunk_run_activity", ["activity_id"], unique=False
        )
        batch_op.create_index(
            "idx_activity_street_chunk_run_way",
            ["way_id", "seq_start", "seq_end"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_activity_street_chunk_runs_activity_id"),
            ["activity_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_activity_street_chunk_runs_way_id"), ["way_id"], unique=False
        )

    op.create_table(
        "street_chunk_visits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("first_activity_id", sa.Integer(), nullable=False),
        sa.Column("first_time", sa.DateTime(), nullable=True),
        sa.Column("last_activity_id", sa.Integer(), nullable=False),
        sa.Column("last_time", sa.DateTime(), nullable=True),
        sa.Column("visit_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["street_chunks.id"], name="street_chunk_visit_chunk_id"
        ),
        sa.ForeignKeyConstraint(
            ["first_activity_id"],
            ["activities.id"],
            name="street_chunk_visit_first_activity_id",
        ),
        sa.ForeignKeyConstraint(
            ["last_activity_id"],
            ["activities.id"],
            name="street_chunk_visit_last_activity_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chunk_id"),
    )
    with op.batch_alter_table("street_chunk_visits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_street_chunk_visits_first_activity_id"),
            ["first_activity_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_street_chunk_visits_last_activity_id"),
            ["last_activity_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("street_chunk_visits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_street_chunk_visits_last_activity_id"))
        batch_op.drop_index(batch_op.f("ix_street_chunk_visits_first_activity_id"))

    op.drop_table("street_chunk_visits")
    with op.batch_alter_table("activity_street_chunk_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_street_chunk_runs_way_id"))
        batch_op.drop_index(batch_op.f("ix_activity_street_chunk_runs_activity_id"))
        batch_op.drop_index("idx_activity_street_chunk_run_way")
        batch_op.drop_index("idx_activity_street_chunk_run_activity")

    op.drop_table("activity_street_chunk_runs")
    with op.batch_alter_table("street_chunks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_street_chunks_way_id"))
        batch_op.drop_index("idx_street_chunks_bbox")

    op.drop_table("street_chunks")
    op.drop_table("street_ways")
    op.drop_table("street_regions")
    op.drop_table("street_nodes")
    # ### end Alembic commands ###
