from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9ebad9ebd18"
down_revision: str | None = "32fb4c78f594"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("maintenance_actions", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=sa.DATETIME(),
            type_=sa.Date(),
            existing_nullable=False,
        )

    with op.batch_alter_table("task_executions", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=sa.DATETIME(),
            type_=sa.Date(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_executions", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=sa.Date(),
            type_=sa.DATETIME(),
            existing_nullable=False,
        )

    with op.batch_alter_table("maintenance_actions", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=sa.Date(),
            type_=sa.DATETIME(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
