from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e55ade5bb5e3"
down_revision: str | None = "52840fd4aab2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "database_maintenance_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_run", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("heatmap_tile_cache", schema=None) as batch_op:
        batch_op.create_index(
            "idx_heatmap_tile_cache_num_activities", ["num_activities"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("heatmap_tile_cache", schema=None) as batch_op:
        batch_op.drop_index("idx_heatmap_tile_cache_num_activities")

    op.drop_table("database_maintenance_state")
    # ### end Alembic commands ###
