from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7c3afa009a4"
down_revision: str | None = "8d6cbf88b1cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_tile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "hillshade_opacity", sa.Float(), server_default="0.5", nullable=False
        ),
        sa.Column(
            "hillshade_blend_mode",
            sa.String(),
            server_default="multiply",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("config_tile")
    # ### end Alembic commands ###
